trigger: none
pool: Tushar_Agent
steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'tushar_service'
    backendAzureRmStorageAccountName: 'shtestt'
    backendAzureRmContainerName: 'shcont'
    backendAzureRmKey: 'pipe.tf'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    backendServiceArm: 'tushar_service'
    backendAzureRmStorageAccountName: 'shtestt'
    backendAzureRmContainerName: 'shcont'
    backendAzureRmKey: 'pipe.tf'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'tushar_service'
    backendAzureRmStorageAccountName: 'shtestt'
    backendAzureRmContainerName: 'shcont'
    backendAzureRmKey: 'pipe.tf'